--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: USER_AUTH_TABLE; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_AUTH_TABLE" (
    password character varying(128) NOT NULL,
    "USER_AUTH_ID" uuid NOT NULL,
    "USERNAME" character varying(256),
    "EMAIL" character varying(100) NOT NULL,
    "IS_STAFF" boolean NOT NULL,
    "IS_ACTIVE" boolean NOT NULL,
    "IS_VERIFIED" boolean NOT NULL,
    "IS_SUPERUSER" boolean NOT NULL,
    "IS_APPROVED" boolean NOT NULL,
    "LAST_LOGIN" timestamp with time zone,
    "CREATED_DATE" timestamp with time zone NOT NULL,
    "UPDATED_DATE" timestamp with time zone NOT NULL
);


ALTER TABLE public."USER_AUTH_TABLE" OWNER TO aptagrim;

--
-- Name: USER_AUTH_TABLE_groups; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_AUTH_TABLE_groups" (
    id bigint NOT NULL,
    usermodel_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public."USER_AUTH_TABLE_groups" OWNER TO aptagrim;

--
-- Name: USER_AUTH_TABLE_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public."USER_AUTH_TABLE_groups" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."USER_AUTH_TABLE_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: USER_AUTH_TABLE_user_permissions; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_AUTH_TABLE_user_permissions" (
    id bigint NOT NULL,
    usermodel_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public."USER_AUTH_TABLE_user_permissions" OWNER TO aptagrim;

--
-- Name: USER_AUTH_TABLE_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public."USER_AUTH_TABLE_user_permissions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."USER_AUTH_TABLE_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: USER_BLACK_LIST_TOKEN_TABLE; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_BLACK_LIST_TOKEN_TABLE" (
    "CORE_GENERIC_CREATED_AT" timestamp with time zone,
    "CORE_GENERIC_LAST_UPDATED_AT" timestamp with time zone,
    "CORE_GENERIC_CREATED_BY" character varying(100),
    "CORE_GENERIC_UPDATED_BY" character varying(100),
    "BLACKLIST_TOKEN_ID" uuid NOT NULL,
    "JWT_TOKEN" text NOT NULL,
    "IS_LOGIN" boolean NOT NULL,
    "IS_DELETE" boolean NOT NULL,
    "USER_ID" uuid NOT NULL
);


ALTER TABLE public."USER_BLACK_LIST_TOKEN_TABLE" OWNER TO aptagrim;

--
-- Name: USER_DETAIL_TABLE; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_DETAIL_TABLE" (
    "CORE_GENERIC_CREATED_AT" timestamp with time zone,
    "CORE_GENERIC_LAST_UPDATED_AT" timestamp with time zone,
    "CORE_GENERIC_CREATED_BY" character varying(100),
    "CORE_GENERIC_UPDATED_BY" character varying(100),
    "USER_AUTH_ID" uuid NOT NULL
);


ALTER TABLE public."USER_DETAIL_TABLE" OWNER TO aptagrim;

--
-- Name: USER_LOGIN_ANALYTICS_TABLE; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public."USER_LOGIN_ANALYTICS_TABLE" (
    "CORE_GENERIC_CREATED_AT" timestamp with time zone,
    "CORE_GENERIC_LAST_UPDATED_AT" timestamp with time zone,
    "CORE_GENERIC_CREATED_BY" character varying(100),
    "CORE_GENERIC_UPDATED_BY" character varying(100),
    "USER_LOGIN_ANALYTICS_ID" uuid NOT NULL,
    "IP_ADDRESS" character varying(255),
    "LOGIN_COUNT" integer NOT NULL,
    "DEVICE_NAME" character varying(255) NOT NULL,
    "TOKEN" text,
    "USER_ID" uuid NOT NULL
);


ALTER TABLE public."USER_LOGIN_ANALYTICS_TABLE" OWNER TO aptagrim;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO aptagrim;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO aptagrim;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO aptagrim;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO aptagrim;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO aptagrim;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO aptagrim;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aptagrim
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: aptagrim
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO aptagrim;

--
-- Name: USER_AUTH_TABLE USER_AUTH_TABLE_EMAIL_key; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE"
    ADD CONSTRAINT "USER_AUTH_TABLE_EMAIL_key" UNIQUE ("EMAIL");


--
-- Name: USER_AUTH_TABLE_groups USER_AUTH_TABLE_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_groups"
    ADD CONSTRAINT "USER_AUTH_TABLE_groups_pkey" PRIMARY KEY (id);


--
-- Name: USER_AUTH_TABLE_groups USER_AUTH_TABLE_groups_usermodel_id_group_id_14a7a1b8_uniq; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_groups"
    ADD CONSTRAINT "USER_AUTH_TABLE_groups_usermodel_id_group_id_14a7a1b8_uniq" UNIQUE (usermodel_id, group_id);


--
-- Name: USER_AUTH_TABLE USER_AUTH_TABLE_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE"
    ADD CONSTRAINT "USER_AUTH_TABLE_pkey" PRIMARY KEY ("USER_AUTH_ID");


--
-- Name: USER_AUTH_TABLE_user_permissions USER_AUTH_TABLE_user_per_usermodel_id_permission__e4f76d27_uniq; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_user_permissions"
    ADD CONSTRAINT "USER_AUTH_TABLE_user_per_usermodel_id_permission__e4f76d27_uniq" UNIQUE (usermodel_id, permission_id);


--
-- Name: USER_AUTH_TABLE_user_permissions USER_AUTH_TABLE_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_user_permissions"
    ADD CONSTRAINT "USER_AUTH_TABLE_user_permissions_pkey" PRIMARY KEY (id);


--
-- Name: USER_BLACK_LIST_TOKEN_TABLE USER_BLACK_LIST_TOKEN_TABLE_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_BLACK_LIST_TOKEN_TABLE"
    ADD CONSTRAINT "USER_BLACK_LIST_TOKEN_TABLE_pkey" PRIMARY KEY ("BLACKLIST_TOKEN_ID");


--
-- Name: USER_DETAIL_TABLE USER_DETAIL_TABLE_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_DETAIL_TABLE"
    ADD CONSTRAINT "USER_DETAIL_TABLE_pkey" PRIMARY KEY ("USER_AUTH_ID");


--
-- Name: USER_LOGIN_ANALYTICS_TABLE USER_LOGIN_ANALYTICS_TABLE_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_LOGIN_ANALYTICS_TABLE"
    ADD CONSTRAINT "USER_LOGIN_ANALYTICS_TABLE_pkey" PRIMARY KEY ("USER_LOGIN_ANALYTICS_ID");


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: USER_AUTH_TABLE_EMAIL_64f20fa7_like; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_AUTH_TABLE_EMAIL_64f20fa7_like" ON public."USER_AUTH_TABLE" USING btree ("EMAIL" varchar_pattern_ops);


--
-- Name: USER_AUTH_TABLE_groups_group_id_9076b074; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_AUTH_TABLE_groups_group_id_9076b074" ON public."USER_AUTH_TABLE_groups" USING btree (group_id);


--
-- Name: USER_AUTH_TABLE_groups_usermodel_id_62c9e336; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_AUTH_TABLE_groups_usermodel_id_62c9e336" ON public."USER_AUTH_TABLE_groups" USING btree (usermodel_id);


--
-- Name: USER_AUTH_TABLE_user_permissions_permission_id_86a4960b; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_AUTH_TABLE_user_permissions_permission_id_86a4960b" ON public."USER_AUTH_TABLE_user_permissions" USING btree (permission_id);


--
-- Name: USER_AUTH_TABLE_user_permissions_usermodel_id_5db43b77; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_AUTH_TABLE_user_permissions_usermodel_id_5db43b77" ON public."USER_AUTH_TABLE_user_permissions" USING btree (usermodel_id);


--
-- Name: USER_BLACK_LIST_TOKEN_TABLE_USER_ID_2b95ce34; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_BLACK_LIST_TOKEN_TABLE_USER_ID_2b95ce34" ON public."USER_BLACK_LIST_TOKEN_TABLE" USING btree ("USER_ID");


--
-- Name: USER_LOGIN_ANALYTICS_TABLE_USER_ID_41242b87; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX "USER_LOGIN_ANALYTICS_TABLE_USER_ID_41242b87" ON public."USER_LOGIN_ANALYTICS_TABLE" USING btree ("USER_ID");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: aptagrim
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: USER_AUTH_TABLE_groups USER_AUTH_TABLE_grou_usermodel_id_62c9e336_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_groups"
    ADD CONSTRAINT "USER_AUTH_TABLE_grou_usermodel_id_62c9e336_fk_USER_AUTH" FOREIGN KEY (usermodel_id) REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_AUTH_TABLE_groups USER_AUTH_TABLE_groups_group_id_9076b074_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_groups"
    ADD CONSTRAINT "USER_AUTH_TABLE_groups_group_id_9076b074_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_AUTH_TABLE_user_permissions USER_AUTH_TABLE_user_permission_id_86a4960b_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_user_permissions"
    ADD CONSTRAINT "USER_AUTH_TABLE_user_permission_id_86a4960b_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_AUTH_TABLE_user_permissions USER_AUTH_TABLE_user_usermodel_id_5db43b77_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_AUTH_TABLE_user_permissions"
    ADD CONSTRAINT "USER_AUTH_TABLE_user_usermodel_id_5db43b77_fk_USER_AUTH" FOREIGN KEY (usermodel_id) REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_BLACK_LIST_TOKEN_TABLE USER_BLACK_LIST_TOKE_USER_ID_2b95ce34_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_BLACK_LIST_TOKEN_TABLE"
    ADD CONSTRAINT "USER_BLACK_LIST_TOKE_USER_ID_2b95ce34_fk_USER_AUTH" FOREIGN KEY ("USER_ID") REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_DETAIL_TABLE USER_DETAIL_TABLE_USER_AUTH_ID_50ae4b05_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_DETAIL_TABLE"
    ADD CONSTRAINT "USER_DETAIL_TABLE_USER_AUTH_ID_50ae4b05_fk_USER_AUTH" FOREIGN KEY ("USER_AUTH_ID") REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: USER_LOGIN_ANALYTICS_TABLE USER_LOGIN_ANALYTICS_USER_ID_41242b87_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public."USER_LOGIN_ANALYTICS_TABLE"
    ADD CONSTRAINT "USER_LOGIN_ANALYTICS_USER_ID_41242b87_fk_USER_AUTH" FOREIGN KEY ("USER_ID") REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_USER_AUTH; Type: FK CONSTRAINT; Schema: public; Owner: aptagrim
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_USER_AUTH" FOREIGN KEY (user_id) REFERENCES public."USER_AUTH_TABLE"("USER_AUTH_ID") DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--
